# Use a lightweight Python image
FROM python:3.11-slim

# Prevents Python from buffering stdout/stderr
ENV PYTHONUNBUFFERED=1

# Set working directory inside container
WORKDIR /app

# Copy dependency file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir -p uploads

# Copy the rest of your app
COPY . .

# CHANGE HERE: Use 1B model (600MB) instead of 3B (3.8GB)
RUN ollama serve & sleep 10 && ollama pull llama3.2:1b

# Expose port for FastAPI
EXPOSE 8000

# Default command to run your app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]


##### CMD ["gunicorn", "main:app", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]